export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
}


export const userConstant = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'

}

export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
};

export const initialDataConstant = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}

export const productConstant = {
    GET_PRODUCT_BY_SLUG_SUCCESS: 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_REQUEST: 'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE',
    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",

    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};